### ISSUE TITLE
ERROR Error: StaticInjectorError[NgZone]: 

### ISSUE THREAD

**Issue by yudream** [wpcfan/taskmgr#22]
hello，

首先感谢大神的分享。
目前我遇到一个问题：我在安装好所有依赖并yarn start后，页面空白，控制台报这个错误
![image](https://user-images.githubusercontent.com/5255465/36153737-31c25f66-110a-11e8-928f-1aea79401343.png)

网上搜了很多解决方案，也照做了，比如
1. import { HttpModule } from '@angular/http';
2. Add "HttpModule" in imports array list.
但没啥效果
有什么建议可以给到我吗？感谢

**Comment by wpcfan** [comment]
fixed #22
