### ISSUE TITLE
这个控件以及地址输入控件的模版中应该用ngModelChange，否则不起作用

### ISSUE THREAD

**Issue by TanYiBing** [wpcfan/taskmgr#23]
https://github.com/wpcfan/taskmgr/blob/e9fcba86107205c7de1a1e890a3ad9d36de23b96/src/app/shared/components/identity-input.ts#L45

**Comment by TanYiBing** [comment]
好像是select的使用ngModelChange才能接受到变化

**Comment by wpcfan** [comment]
新版的 api 变了，可以去  https://material.angular.io/components/select/api 看一下。我有时间改一下
